### 获取token -- 登录功能实现
POST http://127.0.0.1:7000/ecommerce-authority-center/authority/token
Content-Type: application/json

{
  "username": "ImoocQinyi@imooc.com",
  "password": "202cb962ac59075b964b07152d234b70"
}


### 注册用户并返回Token -- 注册功能实现
POST http://127.0.0.1:7000/ecommerce-authority-center/authority/register
Content-Type: application/json

{
  "username": "ImoocQinyi1234@imooc.com",
  "password": "202cb962ac59075b964b07152d234b70"
}