### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiOGQ2ODhhNGEtOGU0ZS00NmM0LWIxY2QtOGFhOGE0NWRiZDM3IiwiZXhwIjoxNjY0MTIxNjAwfQ.Hall3iN3Ykmk3i6n39sgeNfabRQUU2PbZCrcxcC5vtryK8UxpJy2YwEg_pReop6-JJNJWbjPDlmQT0XVgCjFJ8IzKJkenmZtlqAUuAZyOzHUYuJJDVuEveHgUnSr3NRGZOQiSeJdjSjx6bedHLFNqomA-SHWYJpSF4yfTcSqS4gki-7Duy6Rh-D0GrLHrGxdX8IEGegnU7xQ-ATjSnZmax4mMKgb0lrcVSw1iAFser8meEDVeqRCdSPzJQhubyB-gncNnMIShSlO6G7z25t4oj1_5XVZaqVTEsJAmbO5bE3JvQnDyR81xZB2P1GubB_bh1vcwLaN7VAL16gDdJiD-Q
token: imooc