### 获取当前用户余额信息
GET http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/current-balance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiYmNiN2Q3YmQtN2UyNC00Njg5LWE4NDktMDkwZTM5OWM2ZTI2IiwiZXhwIjoxNjY0Mjk0NDAwfQ.L-J8VUZ30WlC_1dNkY0WsmDH10ci9c_Fvmn53506Nd0p4zowR8-jNeGHONgxxhudLQTmNvUyTXnnwt90bh83FaU8kGh3YVcx2xENUdHNfS7PyWhds5Yr-r5V53GOr_wIeHpKe2KeybSws2jPnkRovSiblrT6zfmQTvYXtld6y4j9B8M-Cu3vlADP5ADDQRa8vGfs9a-qEryCAkIm39im9g5BL8jFI7yluMvB7iEub1djax_UtUkzP3QTiKMOKC-OsFS1_pEHFEiw8MGiBr5u_-Dl6TRJP6hJ8nVVfGwmHHbsgRG7oHfuQIm1CHneGue82eHt_9n76IlKKmtdYoXHMg

### 扣减用户余额
PUT http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiYmNiN2Q3YmQtN2UyNC00Njg5LWE4NDktMDkwZTM5OWM2ZTI2IiwiZXhwIjoxNjY0Mjk0NDAwfQ.L-J8VUZ30WlC_1dNkY0WsmDH10ci9c_Fvmn53506Nd0p4zowR8-jNeGHONgxxhudLQTmNvUyTXnnwt90bh83FaU8kGh3YVcx2xENUdHNfS7PyWhds5Yr-r5V53GOr_wIeHpKe2KeybSws2jPnkRovSiblrT6zfmQTvYXtld6y4j9B8M-Cu3vlADP5ADDQRa8vGfs9a-qEryCAkIm39im9g5BL8jFI7yluMvB7iEub1djax_UtUkzP3QTiKMOKC-OsFS1_pEHFEiw8MGiBr5u_-Dl6TRJP6hJ8nVVfGwmHHbsgRG7oHfuQIm1CHneGue82eHt_9n76IlKKmtdYoXHMg

{
  "userId": 10,
  "balance": 999999
}
